---
- hosts: "all"
  become: true
  tasks:
  - name: "Install nginx"
    ansible.builtin.apt:
      name: "nginx"
      state: "latest"
      update_cache: true
  handlers:
  - name: "Start nginx"
    service: name=nginx state=started
    
